name: Java CI with Maven and Azul Zulu JDK 18

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Maven Build with Azul Zulu JDK 18
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Azul Zulu JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn -f /home/runner/work/java-hillel/pom.xml clean install